sudo: required
services:
    - docker

before_install:
    - docker build -t switchedfabric/docker-react -f Dockerfile.development .

script:
    - docker run switchedfabric/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: eu-west-1
    app: docker-react
    env: "DockerReact-env-1"
    bucket_name: elasticbeanstalk-eu-west-1-817873630746
    bucket_path: docker-react
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"
    on:
        branch: master
